# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0bH2UGhfnO19mvgPEQIIm8bmilhL5ZF
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from collections import Counter
from matplotlib.colors import ListedColormap

# ─────────────────────────────────────────────────────────────
#  SEMILLA PARA REPRODUCIBILIDAD
# ─────────────────────────────────────────────────────────────
np.random.seed(42)


# =============================================================
#  1. IMPLEMENTACIÓN KNN DESDE CERO
# =============================================================

def distancia_euclidiana(x1, x2):
    """Calcula la distancia euclidiana entre dos puntos."""
    return np.sqrt(np.sum((x1 - x2) ** 2))


class KNN:
    """
    Implementación de K-Nearest Neighbors desde cero.
    Sin uso de sklearn para el clasificador.
    """

    def __init__(self, k=3):
        self.k = k
        self.X_train = None
        self.y_train = None

    def fit(self, X, y):
        """Entrenar = simplemente almacenar los datos."""
        self.X_train = X
        self.y_train = y

    def predecir_uno(self, x):
        """Predice la clase de un único punto."""
        distancias = [distancia_euclidiana(x, x_train)
                      for x_train in self.X_train]
        indices_k = np.argsort(distancias)[:self.k]
        etiquetas_k = [self.y_train[i] for i in indices_k]
        conteo = Counter(etiquetas_k)
        return conteo.most_common(1)[0][0]

    def predecir(self, X):
        """Predice las clases de múltiples puntos."""
        return np.array([self.predecir_uno(x) for x in X])

    def accuracy(self, X, y):
        """Calcula la precisión del modelo."""
        predicciones = self.predecir(X)
        return np.mean(predicciones == y)


# =============================================================
#  2. FUNCIONES AUXILIARES
# =============================================================

def train_test_split_manual(X, y, test_size=0.3):
    """División manual train/test sin sklearn."""
    n = len(X)
    n_test = int(n * test_size)
    indices = np.random.permutation(n)
    test_idx = indices[:n_test]
    train_idx = indices[n_test:]
    return X[train_idx], X[test_idx], y[train_idx], y[test_idx]


def normalizar(X_train, X_test):
    """Normalización min-max usando solo estadísticas de train."""
    X_min = X_train.min(axis=0)
    X_max = X_train.max(axis=0)
    rango = X_max - X_min
    rango[rango == 0] = 1  # evitar división por cero
    X_train_norm = (X_train - X_min) / rango
    X_test_norm  = (X_test  - X_min) / rango
    return X_train_norm, X_test_norm


def graficar_frontera(ax, modelo, X, y, titulo, k, acc,
                      colores_mapa, colores_puntos):
    """
    Grafica la frontera de decisión de un modelo KNN
    sobre un espacio 2D usando solo las primeras 2 features.
    """
    h = 0.05
    x_min, x_max = X[:, 0].min() - 0.1, X[:, 0].max() + 0.1
    y_min, y_max = X[:, 1].min() - 0.1, X[:, 1].max() + 0.1

    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))

    malla = np.c_[xx.ravel(), yy.ravel()]
    Z = modelo.predecir(malla)
    Z = Z.reshape(xx.shape)

    ax.contourf(xx, yy, Z, alpha=0.3, cmap=colores_mapa)
    ax.scatter(X[:, 0], X[:, 1], c=y,
               cmap=colores_mapa, edgecolors='k',
               linewidths=0.5, s=40)
    ax.set_title(f"{titulo}\nK={k} | Accuracy={acc:.2%}",
                 fontsize=10, fontweight='bold')
    ax.set_xlabel("Feature 1")
    ax.set_ylabel("Feature 2")


# =============================================================
#  3. ANÁLISIS PRINCIPAL
# =============================================================

def analizar_dataset_csv(ruta_csv, nombre_dataset, columna_target,
                         nombre_salida):

    print("\n" + "=" * 60)
    print(f"  ANÁLISIS: {nombre_dataset}")
    print("=" * 60)

    # ── Cargar dataset ────────────────────────────────────────
    df = pd.read_csv(ruta_csv)

    print("\nPrimeras filas del dataset:")
    print(df.head())

    print("\nColumnas detectadas:")
    print(df.columns.tolist())

    X = df.drop(columns=[columna_target]).values
    y = df[columna_target].values

    print(f"\nFeatures usadas : {df.drop(columns=[columna_target]).columns.tolist()}")
    print(f"Target usado    : {columna_target}")
    print(f"Total de datos  : {len(X)}")
    print(f"Clases          : {np.unique(y)}")

    # ── Train/test + normalización ────────────────────────────
    X_train, X_test, y_train, y_test = train_test_split_manual(X, y, test_size=0.3)
    X_train, X_test = normalizar(X_train, X_test)

    n_train = len(X_train)
    k_sqrt  = max(1, int(np.sqrt(n_train)))
    k_max   = min(50, n_train)
    k_range = range(1, k_max + 1)

    print(f"\nn_train = {n_train}")
    print(f"K = sqrt({n_train}) = {k_sqrt}")

    # ── Evaluar todos los K ───────────────────────────────────
    acc_train = []
    acc_test  = []
    mejor_k   = 1
    mejor_acc = 0.0

    print(f"\n{'K':>4} | {'Train Acc':>10} | {'Test Acc':>10}")
    print("-" * 35)

    for k in k_range:
        modelo = KNN(k=k)
        modelo.fit(X_train, y_train)

        acc_tr = modelo.accuracy(X_train, y_train)
        acc_te = modelo.accuracy(X_test,  y_test)

        acc_train.append(acc_tr)
        acc_test.append(acc_te)

        marca = " ← K=sqrt(n)" if k == k_sqrt else ""

        if acc_te > mejor_acc:
            mejor_acc = acc_te
            mejor_k   = k

        print(f"K={k:2d} | Train={acc_tr:.2%} | Test={acc_te:.2%}{marca}")

    print(f"\n* Mejor K encontrado : K={mejor_k}")
    print(f"* Mejor Test Accuracy: {mejor_acc:.2%}")
    print(
        f">>> ¿Coincide con K=sqrt(n)={k_sqrt}?",
        "Sí" if mejor_k == k_sqrt else "No"
    )

    # ── Criterio numérico: menor K con acc óptimo y gap bajo ──
    umbral_acc = 0.99 * mejor_acc   # dentro del 1% del máximo
    umbral_gap = 0.05               # brecha train-test tolerable

    k_optimo = mejor_k              # fallback
    for i, k in enumerate(k_range):
        gap = acc_train[i] - acc_test[i]
        if acc_test[i] >= umbral_acc and gap < umbral_gap:
            k_optimo = k
            break

    print(f"\n* K óptimo por criterio numérico (acc + gap): K={k_optimo}")
    print(f"  → Gap  train-test : {acc_train[k_optimo-1] - acc_test[k_optimo-1]:.2%}")
    print(f"  → Test accuracy   : {acc_test[k_optimo-1]:.2%}")
    print(f"  (Validar visualmente que la frontera no presente islas)")

    # ── Colores según número de clases ───────────────────────
    clases = np.unique(y)
    if len(clases) == 2:
        colores_mapa = ListedColormap(['#AADDFF', '#FFAAAA'])
    elif len(clases) == 3:
        colores_mapa = ListedColormap(['#AADDFF', '#FFAAAA', '#AAFFAA'])
    else:
        colores_mapa = ListedColormap(plt.cm.tab10.colors[:len(clases)])

    # ==========================================================
    #  FIGURA 1 — Análisis completo (3 fronteras + curva)
    # ==========================================================
    valores_k = list(dict.fromkeys([1, k_sqrt, mejor_k]))  # sin repetidos

    fig = plt.figure(figsize=(16, 10), constrained_layout=True)
    fig.suptitle(f"{nombre_dataset} — Análisis KNN",
                 fontsize=14, fontweight='bold')
    gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.5, wspace=0.4)

    for idx, k_val in enumerate(valores_k):
        modelo = KNN(k=k_val)
        modelo.fit(X_train, y_train)
        acc = modelo.accuracy(X_test, y_test)

        if k_val == 1:
            etiqueta = "K=1 (muy pequeño)"
        elif k_val == k_sqrt:
            etiqueta = f"K={k_val} = √n"
        else:
            etiqueta = f"K={k_val} (mejor K)"

        ax = fig.add_subplot(gs[0, idx])
        graficar_frontera(ax, modelo, X_test, y_test,
                          etiqueta, k_val, acc, colores_mapa, None)

    # Espacios vacíos si algún K se repitió
    for idx in range(len(valores_k), 3):
        fig.add_subplot(gs[0, idx]).axis("off")

    # Curva accuracy vs K
    ax_curve = fig.add_subplot(gs[1, :])
    ax_curve.plot(list(k_range), acc_train, 'b-o', markersize=4,
                  label='Train accuracy', linewidth=1.5)
    ax_curve.plot(list(k_range), acc_test,  'r-s', markersize=4,
                  label='Test accuracy',  linewidth=1.5)
    ax_curve.axvline(x=k_sqrt,   color='green',  linestyle='--',
                     linewidth=2, label=f'K=√n={k_sqrt}')
    ax_curve.axvline(x=mejor_k,  color='purple', linestyle='--',
                     linewidth=2, label=f'Mejor K={mejor_k}')
    ax_curve.axvline(x=k_optimo, color='orange', linestyle=':',
                     linewidth=2, label=f'K óptimo (criterio)={k_optimo}')
    ax_curve.set_xlabel("Valor de K")
    ax_curve.set_ylabel("Accuracy")
    ax_curve.set_title(f"Accuracy vs K — {nombre_dataset}")
    ax_curve.set_ylim([0, 1.05])
    ax_curve.grid(True, alpha=0.3)
    ax_curve.legend(fontsize=8)

    plt.savefig(nombre_salida, dpi=120, bbox_inches='tight')
    print(f"\n  Gráfico principal guardado : {nombre_salida}")

    # ==========================================================
    #  FIGURA 2 — Validación visual de K óptimo
    # ==========================================================
    fig_val, ax_val = plt.subplots(figsize=(6, 5))

    modelo_optimo = KNN(k=k_optimo)
    modelo_optimo.fit(X_train, y_train)
    acc_opt = modelo_optimo.accuracy(X_test, y_test)

    graficar_frontera(
        ax_val, modelo_optimo, X_test, y_test,
        f"Validación visual — K={k_optimo} (criterio numérico)",
        k_optimo, acc_opt, colores_mapa, None
    )

    fig_val.tight_layout()
    nombre_validacion = nombre_salida.replace('.png', '_validacion_k_optimo.png')
    plt.savefig(nombre_validacion, dpi=120, bbox_inches='tight')
    print(f"  Gráfico de validación guardado: {nombre_validacion}")


# =============================================================
#  MAIN
# =============================================================

if __name__ == "__main__":

    analizar_dataset_csv(
        ruta_csv       = "dataset_A.csv",
        nombre_dataset = "Dataset A",
        columna_target = "calidad",
        nombre_salida  = "resultado_dataset_A.png"
    )

    plt.show()

    print("\n" + "=" * 60)
    print("  Análisis completado.")
    print("  Archivos generados:")
    print("    → resultado_dataset_A.png")
    print("    → resultado_dataset_A_validacion_k_optimo.png")
    print("=" * 60 + "\n")